name: Build Server Package
'on':
  push:
    paths:
      - 'server/**'
defaults:
  run:
    working-directory: server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build