name: Build Server Package
'on':
  push:
    branches:
      - main
defaults:
  run:
    working-directory: server
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build