name: Build Unity Game Client
'on':
  push:
    paths:
      - 'client/**'
defaults:
  run:
    working-directory: client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2